### PR TITLE
Use Ruby 2.7.2 for development and CI

### PR DESCRIPTION
**Pull request by VSPPedro**
I made the update following the changes made on this PR #1310.

What do you think about dropping the support for old Ruby versions and Rails 4.2 like suggested in this comment: https://github.com/thoughtbot/shoulda-matchers/pull/1324#issuecomment-664078521

One of the advantages would be the reduction of time of the CI.

### CODE REVIEW

**Comment by mcmire** [comment]
@VSPPedro I think that depends on whether we are ready to talk about 5.0. If we're going to be talking about that then perhaps we should although think about other things we could possibly deprecate? For instance, I really wonder how often controller matchers get used (they're more useful in a Minitest context, but even controller tests are deprecated now in Rails). Do we really need database column matchers? etc. But maybe it's worth starting that discussion.

**Comment by mcmire** [comment]
Aside from that, this looks good, so I'll merge :)

**Comment by VSPPedro** [comment]
@mcmire I think it's worth starting that discussion too. Should we finish the open [milestone](https://github.com/thoughtbot/shoulda-matchers/milestone/14) first?

**Comment by mcmire** [comment]
@VSPPedro Eh... maybe. 😆 I made that milestone a while back just so the next release would be somewhat focused instead of cramming as much stuff as possible into one release as I have done in years past. Also, with every new release, I have tried to make sure I am addressing old issues as well as new ones, but at this point that strategy has failed too 🙄

So... I say if we want to release a new major version, we should focus on that and everything that entails and not worry so much about what it is in the backlog (unless there's something we've always wanted to fix that requires a backward incompatible change — although I'm having a hard time thinking of an example right now).

**Comment by VSPPedro** [comment]
I'll try to help to finish that milestone. :smile:

**Comment by KapilSachdev** [comment]
Good catch @VSPPedro . I have created `4.5.0` milestone, and is adding PRs that are merged after 4.4.1 under it. I hope i don't miss any.

> So... I say if we want to release a new major version

I think our major release (`5.0.0`) will be the one where we would be removing the support for rails `4.2` for which we would be creating a deprecation workflow.
So I have taken the liberty to create a `4.5.0` milestone which would be our next version.

**Comment by mcmire** [comment]
@VSPPedro I gave @KapilSachdev commit access and it sounds like you may want to do more work so I have given you commit access as well. I will let y'all coordinate on what you want to include in 4.5.0 :)

**Comment by VSPPedro** [comment]
Thank you very much!

**Pull request merged**
