### PR TITLE
WIP: Add support for Rails 5

### PR DESCRIPTION
**Pull request by mcmire**
- [ ] Fix `validate_inclusion_of` so that it only checks if `minimum` is 0 if the column is a numeric column
- [ ] Fix places where we are using controller test helpers (`get`, `post`, etc.) so that they use keyword arguments (#867, fixed by #964)
- [ ] Fix `serialize` so that it does not refer to `cast_type` (#913)
- [x] Instead of referring to just `connection.tables`, use `connection.data_sources` (#933, fixed by #943)
- [ ] Fix compatibility with JRuby / JDBC (#944)
- [ ] Fix `have_db_index` so it works with expressions as well as columns (#945)
- [ ] Fix `validate_uniqueness_of` when used with a boolean so it doesn't produce a warning (#949)
- [ ] Modify `route` to support a `port` option (#954)
- [ ] Fix `validate_presence_of` as the validation message changed ([#861](https://github.com/thoughtbot/shoulda-matchers/issues/861#issuecomment-189563425))

### CODE REVIEW

**Comment by stevebissett** [comment]
I came across this from:
http://stackoverflow.com/questions/39611716/how-do-i-test-associations-in-models-with-rspec-in-rails-5?noredirect=1#comment66531045_39611716

@mcmire - do you have any idea on when you might be done with this? Appreciate the work BTW.

**Comment by mcmire** [comment]
Hey @stevebissett,

Sorry for the wait on this. Unfortunately I don't really have a timeline for when this will be complete. I tend to work on it whenever I have time and I haven't had a whole lot of that lately.

**Comment by aried3r** [comment]
Hey @mcmire, I saw you sadly no longer have the time to maintain this project. I wanna start off by saying Thanks! for all your efforts so far! 👍 

But wrt to this PR, would you be open to drop the conditionals for ActiveModel 3 and maybe some older Rails 4.x versions in favor of supporting Rails 5.0 and the upcoming 5.1 which will remove a lot of deprecated functions. It would require a new major release, but also means that there would be a working version of shoulda-matchers (3.x) for older Rails versions and a new, lighter version (because of dropping support) of it?

I even see `unless active_model_3_2? || active_model_4_0?` in this PR (although just moved).

**Comment by mcmire** [comment]
@aried3r Thanks for the support, it means a lot. :) Yeah, I am totally open to that. In fact for shoulda I have already removed support for Rails < 4.2: https://github.com/thoughtbot/shoulda/commit/b9353e29cdfbc484bfd808df55226bb26d0fc4a5, so I think we could definitely do the same thing here and release a new major version.

**Comment by em77** [comment]
Hey @mcmire I just wanted to check in and see if there's any update on the timeline for this. I appreciate all the work you've put into this project and would like to see it continue to be compatible with Rails versions going into the future!

**Comment by guialbuk** [comment]
Hi, @em77 .
The Rails 5 support is in progress but it can be used in production (I'm using in two Rails 5.1 projects)
Point you Gemfile to ```rails-5``` branch and you are good to go :)
https://github.com/thoughtbot/shoulda-matchers#getting-started

**Comment by em77** [comment]
@guialbuk Hey thanks for the encouraging reply. So that branch is considered safe for rails 5.1? Is there any documentation of what methods or functionality are _not_ working properly on rails 5.0 and 5.1?

**Comment by guialbuk** [comment]
@em77 It is safe to use on Rails 5.0 and 5.1 The list on the top of this PR (```rails5``` branch, not ```rails-5```) is not up to date and many issues have been solved. Even Ruby 2.4 is supported in the ```rails-5```branch.
The ```rails-5```branch will soon be merged into ```master``` and become ```4.0.beta1``` version.

**Comment by mcmire** [comment]
@guialbuk I wonder if it would be helpful to keep this list up to date while the `rails-5` branch is WIP (this way everyone knows, and it helps me triage things). I know you've merged the `tables` PR (#943) -- is there anything else that your branch has fixed, or is that it for now?

**Comment by mcmire** [comment]
Actually I think what I'll do is close this and move this to an issue so it's not confusing. But I'd still like to keep a list :)

**Pull request closed without merging**
