### PR TITLE
Added validate_absence_of and validate_acceptance_of

### PR DESCRIPTION
**Pull request by Lrcezimbra**
Adding this two matchers to the README

### CODE REVIEW

**Comment by mcmire** [comment]
Good catch, thanks.

**Comment by mcmire** [comment]
3.0.0 is feature-frozen, so I'll merge this in for 3.1.0.

**Comment by calebthompson** [comment]
Is lack of documentation a bug?

**Comment by mcmire** [comment]
I wouldn't say so. It doesn't really hold up the release.

**Comment by mcmire** [comment]
I opted to merge this in now since it's a documentation update. Thanks for the PR!

Merged as fc78a2d45220aca01ab7c3155a6a3ebe943fc85b.

**Pull request closed without merging**
