### PR TITLE
Replace Fixnum with Integer

### PR DESCRIPTION
**Pull request by dorobica**
Fixes https://github.com/thoughtbot/shoulda-matchers/issues/1001

### CODE REVIEW

**Comment by danilobytes** [comment]
Some prevision for this going through?

**Comment by lucascaton** [comment]
Any news on this one?

**Comment by danilobytes** [comment]
Please give us nice specs output back 🙏🏼

**Comment by lucascaton** [comment]
cc: @guialbuk

**Comment by guialbuk** [comment]
@danilobytes @lucascaton merged into rails-5 branch. Enjoy it :)

**Pull request merged**
