### PR TITLE
feat: Add github action for linting rubocop

### LINKED ISSUE #1345: Replace Hound with GitHub Action
In the past, this gem was using Hound (developed by some now ex-thoughtbotters) to run code through Rubocop. However, it doesn't seem to be maintained much these days — I actually disabled Hound a while back because it started choking on new versions of Rubocop, starting with the Rubocop team's decision to spin `rubocop-rails` off. Since then GitHub Actions has emerged as a more built-in solution for these types of tasks. I believe there is a linter action out there that integrates with Rubocop, and I think we should try to use that instead.

### PR DESCRIPTION
**Pull request by KapilSachdev**
Closes #1345

### CODE REVIEW

**Comment by mcmire** [comment]
Any way to run this action with an intentional Rubocop violation? Wondering if the `[skip ci]` is also preventing the action from getting run.

**Comment by KapilSachdev** [comment]
I did try its behaviour [before](https://github.com/KapilSachdev/shoulda-matchers/pull/1/files) creating a PR here, but it seems the action didn't run here which i thought would run.
I don't think [ci skip] have any effect, as I force pushed it twice and previous commit message does not had [ci skip] and the action didn't ran.
I will force push again without [ci skip], just to verify.

**Comment by KapilSachdev** [comment]
Amending the commit and PR text with no [ci skip] does not had any effect.
Might be related to repository permissions? I'm not sure, but it seems to be working in my forked one.

**Comment by mcmire** [comment]
Weird. Just checked out your repo though and everything looks good here.

By the way I see that you've been contributing a lot lately. Do you plan on doing more work? I can give you commit access if so.

**Comment by KapilSachdev** [comment]
>Do you plan on doing more work? 

Yes.

**Review by mcmire — APPROVED** [review]

**Comment by mcmire** [comment]
Okay you have commit access now, feel free to merge at will!

**Comment by KapilSachdev** [comment]
Thank You !

**Comment by KapilSachdev** [comment]
As per wearerequired/lint-action#13, The action will give 403 against the fork.
Taking liberty to merge thinking it would work. (as fork one is working properly)

**Pull request merged**
