### PR TITLE
Add assignment method support to delegate_method matcher

### LINKED ISSUE #606: delegate_method not supporting assignment methods
Currently in a project I am doing something like this:

```ruby
class Product < ActiveRecord::Base
  has_one :price

  delegate :amount, :amount=, to: :price
end
```

You can make an inference of how the price model might work, but lets look at how we would test our product model.

```ruby
require 'rails_helper'

describe Product do
  it { should have_one :price }

  it { should delegate_method(:amount).to :price }
  it { should delegate_method(:amount=).to :price }
end
```

The output is as so:

```shell
$ zeus rspec spec/models/product_spec.rb
..F

Failures:

  1) Product should delegate #amount= to #price object
     Failure/Error: it { should delegate_method(:amount=).to :price }
     ArgumentError:
       wrong number of arguments (0 for 1)
     # ./app/models/product.rb:4:in `amount='
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/independent/delegate_method_matcher.rb:268:in `public_send'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/independent/delegate_method_matcher.rb:268:in `block in subject_delegates_to_target_correctly?'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/doublespeak/world.rb:12:in `with_doubles_activated'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/independent/delegate_method_matcher.rb:267:in `subject_delegates_to_target_correctly?'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/shoulda-matchers-2.7.0/lib/shoulda/matchers/independent/delegate_method_matcher.rb:136:in `matches?'
     # ./spec/models/product_spec.rb:7:in `block (2 levels) in <top (required)>'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus/rails.rb:202:in `test'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus.rb:148:in `block in command'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus.rb:135:in `fork'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus.rb:135:in `command'
     # /Users/benmorgan/.rvm/gems/ruby-2.1.2/gems/zeus-0.15.1/lib/zeus.rb:50:in `go'
     # -e:1:in `<main>'

Finished in 0.3338 seconds (files took 1 minute 2.8 seconds to load)
6 examples, 1 failure

Failed examples:

rspec ./spec/models/spree/product_spec.rb:9 # Product should delegate #amount= to #price object
```

Hope this helps :)

### PR DESCRIPTION
**Pull request by st0012**
Fix #606 's wrong argument error when delegate assignment method.

### CODE REVIEW

**Comment by mcmire** [comment]
3.0.0 is feature-frozen, so I'll merge this in for 3.1.0.

**Comment by st0012** [comment]
Got it, thank

**Comment by BenMorganIO** [comment]
:+1: good job @st0012 :D

**Comment by ehannes** [comment]
+1 for this feature

**Comment by nannery** [comment]
+1 as well

**Comment by ehannes** [comment]
Any news on this?

**Comment by st0012** [comment]
@ehannes I didn't get any updates for almost a year 😂

**Comment by ehannes** [comment]
It's labeled "Awaiting Code Review". Maybe they don't have any active reviewers for this repository?

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this PR.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this PR, then please let us know so that we can reprioritize it. Thanks!

**Pull request closed without merging**
