### PR TITLE
Deprecation for ruby 2.4 removed

### PR DESCRIPTION
**Pull request by dima4p**

### CODE REVIEW

**Comment by dima4p** [comment]
And, please, apply the patch to the minor versions of the gem, at least to v2.8.0 since shoulda still requires it.

**Comment by dima4p** [comment]
It seems the tests failed due to the configuration not the code. If I am wrong, what happened?

**Comment by mcmire** [comment]
Hey @dima4p. Thank you for your PR! I just changed it so that it's now based off of the `rails-5` branch which also contains compatibility updates for Ruby 2.4. If you could be so kind as to rebase your branch that would be great! The build is failing right now, so don't worry about that -- we'll merge in your PR when we get that fixed.

**Comment by mcmire** [comment]
@dima4p No need to create a new PR. Pull down the latest changes for `rails-5` and rebase your branch against it. GitHub will let you force-push your branch back up :)

**Comment by mcmire** [comment]
Thanks for this PR! We've merged this in 03a1d21.

**Pull request closed without merging**
