### PR TITLE
Account for composite primary key in foreign key

### PR DESCRIPTION
**Pull request by natematykiewicz**
Fixes [#1392]

### CODE REVIEW

**Comment by natematykiewicz** [comment]
You're totally fine!

**Review by VSPPedro — APPROVED** [review]

**Comment by VSPPedro** [comment]
> I also think some DRYing could happen here between primary and foreign key checks.

I agree with you, but I think we can do that on another PR later. Let's fix this first. :+1:

For now, let's wait for the CI.

If you have the time, @mcmire, can you share your thoughts with us on this?

**Comment by VSPPedro** [comment]
@mcmire, what do you think of this?

I'm thinking of releasing a fix for this - v4.5.1.

**Review by mcmire — APPROVED** [review]
Makes sense to me!

**Comment by VSPPedro** [comment]
Thanks! Merging!

**Comment by VSPPedro** [comment]
Hi @natematykiewicz, I'm sending this message just to let you know that we now have a new version of SholdaMatchers with your contribution! Thank you again!

**Comment by voxik** [comment]
Just FTR, I think there is something about the symbol vs strings, because testing against Rails 6.1, there are two test failures:

~~~
  1) Shoulda::Matchers::ActiveRecord::AssociationMatcher have_one rejects an association with a valid :class_name and :foreign_key option (CPK), but no columns
     Failure/Error:
       expect do
         have_one(:detail).class_name('PersonDetail').
           with_foreign_key(%i[company_id person_detail_id])
       end.not_to match_against(Person.new).and_fail_with(expected_message)
     
       Expected the positive version of the matcher not to match and for the failure
       message to be:
     
       ------------------------------------------------------------------------
       Expected Person to have a has_one association called detail (PersonDetail does not have a ["company_id", "person_detail_id"] foreign key.)
       ------------------------------------------------------------------------
     
       However, it was:
     
       ------------------------------------------------------------------------
       Expected Person to have a has_one association called detail (PersonDetail does not have a [:company_id, :person_detail_id] foreign key.)
       ------------------------------------------------------------------------
     
       Diff:
     # ./spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb:1455:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/bundler-2.2.3/libexec/bundle:49:in `block in <top (required)>'
     # /usr/share/gems/gems/bundler-2.2.3/libexec/bundle:37:in `<top (required)>'

  2) Shoulda::Matchers::ActiveRecord::AssociationMatcher have_one accepts an association with a valid :class_name and :foreign_key option (CPK)
     Failure/Error:
       expect(Person.new).
         to have_one(:detail).
         class_name('PersonDetail').
         with_foreign_key(%i[company_id person_detail_id])
     
       Expected Person to have a has_one association called detail (PersonDetail does not have a [:company_id, :person_detail_id] foreign key.)
     # ./spec/unit/shoulda/matchers/active_record/association_matcher_spec.rb:1467:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/bundler-2.2.3/libexec/bundle:49:in `block in <top (required)>'
     # /usr/share/gems/gems/bundler-2.2.3/libexec/bundle:37:in `<top (required)>'
~~~

**Pull request merged**
