### PR TITLE
make the library work with globally enabled frozen-string-literals

### LINKED ISSUE #1563: The library doesn't work with frozen-string-literals enabled globally.
Hio!

The library using String modification in place in some places, for example:

```ruby
  ''.tap do |preface|
    if descriptions_for_preset_values.any?
      preface << 'After setting '
      preface << descriptions_for_preset_values.to_sentence
      preface << ', then '
    else
      preface << 'After '
    end
. . .
end
```

So, when the application has `frozen-string-literals` enabled globally (instead of per-file "magic" comment) via:
```bash
ENV RUBYOPT='--enable=frozen-string-literal'
```

It raises an error when specs are executed:

```bash
 FrozenError:
   can't modify frozen String: ""
 # /usr/local/share/gems/gems/shoulda-matchers-5.3.0/lib/shoulda/matchers/active_model/allow_value_matcher.rb:550:in `block in default_failure_message_preface'
```

🥲

### PR DESCRIPTION
**Pull request by amalrik**
fixes #1563 
EDIT:after some more verification I noticed we need more changes in order to make the tests pass with the frozen-string option globally enabled. LMK if you guys think this is a useful contribution to project.

### CODE REVIEW

**Comment by amalrik** [comment]
in order to run the tests and see the error you have to run them this way
```bash
RUBYOPT='--enable=frozen-string-literal' bundle exec appraisal rails_7_1 rspec spec/
``` 
and ofc you can replace `rails_7_1` for the other supported appraisals

**Comment by VSPPedro** [comment]
I believe it's a positive step to take. If everyone is in agreement, let's proceed with updating the CI to run with this configuration: RUBYOPT='--enable=frozen-string-literal'

**Comment by amalrik** [comment]
Thanks for the feedback @VSPPedro I will put some hours of work on this issue and update this pull request as I progress

**Comment by VSPPedro** [comment]
Nice work, @amalrik. I think we need to add  RUBYOPT='--enable=frozen-string-literal' to the CI configuration to be sure that is working. What do you think?

https://github.com/thoughtbot/shoulda-matchers/blob/d611911f0175fe6712025dac9f150b0a741d43c0/.github/workflows/ci.yml#L64

https://github.com/thoughtbot/shoulda-matchers/blob/d611911f0175fe6712025dac9f150b0a741d43c0/.github/workflows/ci.yml#L66

**Comment by amalrik** [comment]
> Nice work, @amalrik. I think we need to add RUBYOPT='--enable=frozen-string-literal' to the CI configuration to be sure that is working. What do you think?
> 
> https://github.com/thoughtbot/shoulda-matchers/blob/d611911f0175fe6712025dac9f150b0a741d43c0/.github/workflows/ci.yml#L64
> 
> https://github.com/thoughtbot/shoulda-matchers/blob/d611911f0175fe6712025dac9f150b0a741d43c0/.github/workflows/ci.yml#L66

tks man I agree.
I just added the option on CI but let me know if you'd rather to run tests with and without the option. I think maybe its not necessary but LMK your opinion and if I should squash commits as well.

**Comment by VSPPedro** [comment]
To be honest, I'm not a fan of it, but I think it's a good thing to have to ensure that we aren't introducing anything that could inadvertently alter a string and potentially disrupt this feature.

Let me check how other gems approach this.

**Comment by amalrik** [comment]
hey @VSPPedro could you check this?
LMK if I can help you moving this forward

**Review by VSPPedro — APPROVED** [review]
LGTM! Sorry for taking so long. Please, squash the commits.

**Pull request merged**
