### PR TITLE
Create the allow_values matcher

### LINKED ISSUE #562: Array version of `allow_value`
Sometimes you need to see if some values are allowed for a defined field and using the current features you would have to use many `allow_value().for()` constructs. It would be nice to have a array version, like `allow_values('foo', 'bar').for()`.

### PR DESCRIPTION
**Pull request by maurogeorge**
Closes #562

### CODE REVIEW

**Comment by mcmire** [comment]
Thanks for the PR -- I'm actually already working on this. I'd like to change `allow_value` so it only accepts one attribute and not multiple -- `allow_values` will be responsible for testing multiple values, if that's what you'd like (and that way we can move the `match?` / `does_not_match?` logic there, instead).

**Comment by maurogeorge** [comment]
@mcmire cool, your implementation make more sense. I will close this PR since it add only a alias, we can continue using the `allow_value` to multiple values until the release of the 3.0.

**Comment by mcmire** [comment]
I changed my mind about creating a separate `allow_values` matcher -- after playing around it a bit, I think it's an unnecessary backward incompatibility and it's not worth having to write separate tests for. 

So I went ahead and merged this: ae77c7d736664876ddea726beee92c7888090783. I'll probably end up switching it around so that `allow_values` is the "real"  matcher and `allow_value` is the alias (since it is designed to accept multiple values after all).

**Comment by maurogeorge** [comment]
:+1: makes sense to me.

**Pull request closed without merging**
