### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by ojab**

### CODE REVIEW

**Comment by mcmire** [comment]
@ojab Thanks for this. I imagine there is a test missing for this. Do you think you could add that?

**Comment by ojab** [comment]
yep, will do tomorrow or so.
BTW can you tell me how houncl tests PRs? I assume rubocop, but not sure about settings. I'd like to add this info to the CONTRIBUTING.md.

**Comment by mcmire** [comment]
@ojab Yes, Hound uses Rubocop, but we (thoughtbot) have slightly different style rules than what comes with Rubocop by default, and so this project uses those rules instead. You can see them [here](https://github.com/thoughtbot/hound/blob/master/config/style_guides/thoughtbot/ruby.yml).

**Comment by ojab** [comment]
Updated PR, now there is a test.

**Comment by mcmire** [comment]
Oh yeah, I forgot to mention -- some of the styles that are in Hound have changed over time, so we have a local hound.yml file in this repo to revert those style changes. That file is here: https://github.com/thoughtbot/shoulda-matchers/blob/master/.hound_config/ruby.yml. That's why you're getting a message from Hound above about single quotes. No matter -- I'll clean this up.

**Comment by mcmire** [comment]
Thanks! Merged as 1dbf71bfe591f110d4a3c8e412c2c41329657ad6.

**Pull request closed without merging**
