### PR TITLE
Bump Rubocop from 0.71.0 to 0.89.1

### PR DESCRIPTION
**Pull request by VSPPedro**
I noticed that my plugin for Rubocop on VSCode was not working properly.

Every time I open a .rb file it raises this warning:

```
/home/pedro/.rvm/gems/ruby-2.7.1/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:84: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call /home/pedro/.rvm/gems/ruby-2.7.1/gems/rubocop-0.71.0/lib/rubocop/config_loader_resolver.rb:92: warning: The called method `merge' is defined here...
```

So I decided to update Rubocop to the latest version and see what happens.

Then, the warnings changed to:

```
The Metrics/LineLength has the wrong namespace
- should be Layout Error: 
The `Layout/AlignArguments` cop has been renamed to `Layout/ArgumentAlignment`. (obsolete configuration found in .rubocop.yml, please update it) 
The `Layout/AlignParameters` cop has been renamed to `Layout/ParameterAlignment`. (obsolete configuration found in .rubocop.yml, please update it) 
The `Layout/IndentHeredoc` cop has been renamed to `Layout/HeredocIndentation`. (obsolete configuration found in .rubocop.yml, please update it) 
The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`. (obsolete configuration found in .rubocop.yml, please update it)
```

I made one commit for every warning to be easier if anyone wants to look at the fix of these warnings separately. (I intend to squash if these changes are approved.)

And then, the warnings changed to:

```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Layout/EmptyLinesAroundAttributeAccessor (0.83)
- Layout/SpaceAroundMethodCallOperator (0.82)
- Lint/BinaryOperatorWithIdenticalOperands (0.89)
- Lint/DeprecatedOpenSSLConstant (0.84)
- Lint/DuplicateElsifCondition (0.88)
- Lint/DuplicateRescueException (0.89)
- Lint/EmptyConditionalBody (0.89)
- Lint/FloatComparison (0.89)
- Lint/MissingSuper (0.89)
- Lint/MixedRegexpCaptureTypes (0.85)
- Lint/OutOfRangeRegexpRef (0.89)
- Lint/RaiseException (0.81)
- Lint/SelfAssignment (0.89)
- Lint/StructNewOverride (0.81)
- Lint/TopLevelReturnWithArgument (0.89)
- Lint/UnreachableLoop (0.89)
- Style/AccessorGrouping (0.87)
- Style/ArrayCoercion (0.88)
- Style/BisectedAttrAccessor (0.87)
- Style/CaseLikeIf (0.88)
- Style/ExplicitBlockArgument (0.89)
- Style/ExponentialNotation (0.82)
- Style/GlobalStdStream (0.89)
- Style/HashAsLastAr...
```

Yes, the warning was so big that VSCode was unable to show all the content on my screen.

Fortunately, AllCops has a new parameter to facilitate the configuration of pending cops.

For more information check this PR: https://github.com/rubocop-hq/rubocop/pull/7856

As it stands, all pending cops are disabled, but if we prefer to enable this or perhaps configure each manually, I can work on it.

### CODE REVIEW

**Comment by mcmire** [comment]
Ugh. There's a lot of decisions that the Rubocop team has made that I disagree with, and as you can tell if you look at the history of `.rubocop.yml`, I have progressively disabled cops I've found unnecessary as I've discovered them. I've considered changing `.rubocop.yml` so that all cops are disabled by default and then the cops that are used now are explicitly enabled, but I'm also secretly waiting for [`rubyfmt`](https://github.com/penelopezone/rubyfmt) to be in a state where it can parse most Ruby files without issues so that I don't ever have to deal with Rubocop again... \</rant\>

Anyway, thank you for upgrading this. Let's keep new cops disabled by default, as you have it. What you have here looks good to me and I don't mind if you squash 👌

**Comment by VSPPedro** [comment]
I didn't expect the ruby​​fmt to have so many pieces on Rust. I think I'll take a look later. It's a programming language that I would love to learn more about. Thank you for sharing your thoughts on this project.

> I've considered changing `.rubocop.yml` so that all cops are disabled by default and then the cops that are used now are explicitly enabled

I think is a good idea, will make the `rubocop.yml` leaner.

Do you prefer to add this modification to this PR or another?

Squash and rebase done!

**Comment by mcmire** [comment]
@VSPPedro I think another PR is fine... we can cross that bridge when we get there.

Merged, thank you!

**Comment by KapilSachdev** [comment]
@VSPPedro are you planning on working further in this?
In case you are not working, i can start on it.

Currently rubocop is getting offended too much, not sure if it was giving issues that much before the bump we made to `0.89.1`.
There are some warnings as well for `# rubocop:disable Metrics/LineLength` as rubocop-hq/rubocop#7542 moved it under `Layout` namespace.
Also rubocop have released its `0.90` version and as we are still in transition phase for rubocop, might as well upgrade to latest.

**Comment by VSPPedro** [comment]
@KapilSachdev I am not working on it at the moment. I think it would be amazing if you have time to take a look at it.

**Pull request merged**
