### PR TITLE
adds failure_message_when_negated to have_secure_password_matcher

### LINKED ISSUE #1187: have_secure_password cannot be used in the negative
The `have_secure_password` is missing a `failure_message_when_negated` method, so it cannot be used like this:

``` ruby
it { should_not have_secure_password }
```

### PR DESCRIPTION
**Pull request by amalrik**
closes #1187 
credits goes to @Kutomore Im just adding missing specs to his solution on a new PR because I cant override PR #1192

### CODE REVIEW

**Review by matsales28 — APPROVED** [review]
LGTM!

**Review by VSPPedro — COMMENTED** [review]
Looks good to me! I believe it would be a great idea to squash the commits and include @Kutomore as a co-author.

https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github

What do you think?

**Comment by amalrik** [comment]
> Looks good to me! I believe it would be a great idea to squash the commits and include @Kutomore as a co-author.
> 
> https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-github
> 
> What do you think?

Good idea. Done

**Comment by VSPPedro** [comment]
Thank you for your contribution, @amalrik!

**Pull request merged**
