### PR TITLE
Ruby 3.0 + Rails 6.1

### PR DESCRIPTION
**Pull request by voxik**
This is mostly dupe of #1409, but it contains some additional fixes and two disabled test which fails testing against Rails 6.1.

### CODE REVIEW

**Comment by voxik** [comment]
I had to disable 4 test cases, presumably due to Rails 6.1 incompatibilities, otherwise I am able to execute the test suite against the Ruby 3.0 + Rails 6.1 combination with this patch set. Nonetheless, I have not checked backward compatibility. But according to the github action result, there is just one unexpected issue, so I am quite happy with this :)

Feel free to cherry-pick whatever is needed.

**Comment by mcmire** [comment]
Yeah, we should probably add Rails 6.1 to the list of Appraisals so we can fully verify everything. And 7.0 when it comes out 😭

**Comment by mecampbellsoup** [comment]
Is this expected to be merged soon?

**Comment by VSPPedro** [comment]
@mecampbellsoup, we already have this covered on master. Take a look at this release: https://github.com/thoughtbot/shoulda-matchers/releases/tag/v5.0.0.rc1 and check if it works for you, please.

Thanks, @voxik, for this PR!

**Pull request closed without merging**
