### PR TITLE
Support symbol for `validates_numericality_of`

### PR DESCRIPTION
**Pull request by vyrak**
Have `vaidates_numericality_of` support symbols for feature request #688

### CODE REVIEW

**Comment by totallymike** [comment]
I think this looks pretty good, and am also looking for this feature.

**Comment by MDjavaheri** [comment]
@mcmire Any timetable as to when this will be resolved and merged?

**Comment by mcmire** [comment]
Hey folks. In an effort to lighten our load as maintainers and be able to serve you better in the future, the shoulda-matchers team is working on cleaning out the cobwebs in this repo by pruning the backlog. As there are few of us, there are a lot of items that will simply never earn our attention in a reasonable time frame, and rather than giving you an empty promise, we think it makes more sense to focus on more recent issues. That means, unfortunately, that we must close this PR.

Don't take this the wrong way: our aim is not to diminish the effort people have made or dismiss problems that have been raised. If you feel that we should reopen this PR, then please let us know so that we can reprioritize it. Thanks!

**Comment by bbugh** [comment]
@mcmire can we reopen this? `validate_numericality_of` doesn't support symbol fields which misses out on the rails feature of comparing vs a column. It looks like this was ready to go!

**Pull request closed without merging**
