### PR TITLE
Switch to GitHub Actions

### LINKED ISSUE #1395: Switch to Github Actions or Buildkite
I think we need to change the CI before this happens: `Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.`

You can see this warning at the header on their site: https://travis-ci.org/

I'm creating this issue so I don't forget that detail.

### PR DESCRIPTION
**Pull request by natematykiewicz**
Closes #1395

### CODE REVIEW

**Comment by natematykiewicz** [comment]
The unit tests pass, but the acceptance tests can't find gems. Not sure why.

**Comment by VSPPedro** [comment]
Good PR!

Thank you very much for trying to find a solution to this. To be honest, I didn't know how to help you, so instead, I tried to keep testing my PR and I think I found the fix for CI with github actions. In case you want to know: # 1397. What do you think?

I'm sorry, I never intended to take this contribution from you, I was already working on it when I saw your PR. Anyway, I should have assigned this issue - #1395 - to myself. My bad. If you think we can find a better solution, we can continue working on this PR.

**Comment by natematykiewicz** [comment]
@VSPPedro No apologies necessary! I saw you had a PR open for it and I had recently done a similar PR on a private repo for my work, so I thought maybe I could help somehow.

I saw you were doing a lot of `if`s, so I was hoping seeing the `exclude` in the matrix would help. Glad to see it did help!

If you can, I'd suggest using the bundler-cache option in setup-ruby instead of rolling your own cache. It's got a lot of logic in it that's really nice, and utilizes `bundle check` as well.

**Comment by VSPPedro** [comment]
> I saw you were doing a lot of ifs, so I was hoping seeing the exclude in the matrix would help. Glad to see it did help!

Opps, did you see that?

I was still looking in the documentation for how to improve it. Luckily your PR ended up giving me the solution - the `exclude`.

> If you can, I'd suggest using the bundler-cache option in setup-ruby instead of rolling your own cache. It's got a lot of logic in it that's really nice, and utilizes bundle check as well.

Interesting, I'll try to do that. Thanks again.

**Comment by natematykiewicz** [comment]
> Opps, did you see that?
😉

> Interesting, I'll try to do that. Thanks again.
You’re welcome!

**Pull request closed without merging**
