### PR TITLE
Add RVM (Ruby Version Manager) to setup

### PR DESCRIPTION
**Pull request by mswiszcz**
Setup script will now recognize RVM if that's your preferred ruby manager 😄

### CODE REVIEW

**Comment by mcmire** [comment]
Thanks for this! I can probably guess the answer to this, but I just want to confirm, have you tried this on your machine? I don't use RVM myself so I have to trust other people on this :)

**Comment by mswiszcz** [comment]
Well I had 2.7.2 installed so I've had to check if actually line about "install" works. And it does 😄 I had to change to 2.7.1 to validate that.

Here's how it looks

```sh
~/Labs/shoulda-matchers(master*) » bin/setup
You don't seem to have a Ruby manager installed.

We recommend using asdf. You can find instructions to install it here:

    https://asdf-vm.com

When you're done, close and re-open this terminal tab and re-run this script.
~/Labs/shoulda-matchers(master*) » git co -
M	.tool-versions
Switched to branch 'add-rvm-to-setup'
~/Labs/shoulda-matchers(add-rvm-to-setup*) » bin/setup
== Installing Ruby 2.7.1 with rvm ==
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/11.2/x86_64/ruby-2.7.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Updating certificates bundle '/usr/local/etc/openssl@1.1/cert.pem'
Requirements installation successful.
Installing Ruby from source to: /Users/akra/.rvm/rubies/ruby-2.7.1, this may take a while depending on your cpu(s)...
ruby-2.7.1 - #downloading ruby-2.7.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 14.0M  100 14.0M    0     0  4094k      0  0:00:03  0:00:03 --:--:-- 4094k
ruby-2.7.1 - #extracting ruby-2.7.1 to /Users/akra/.rvm/src/ruby-2.7.1.....
ruby-2.7.1 - #configuring.........................................................................
ruby-2.7.1 - #post-configuration.
ruby-2.7.1 - #compiling........................................................................
ruby-2.7.1 - #installing............
ruby-2.7.1 - #making binaries executable...
Installed rubygems 3.1.2 is newer than 3.0.9 provided with installed ruby, skipping installation, use --force to force installation.
ruby-2.7.1 - #gemset created /Users/akra/.rvm/gems/ruby-2.7.1@global
ruby-2.7.1 - #importing gemset /Users/akra/.rvm/gemsets/global.gems................................................................
ruby-2.7.1 - #generating global wrappers........
ruby-2.7.1 - #gemset created /Users/akra/.rvm/gems/ruby-2.7.1
ruby-2.7.1 - #importing gemsetfile /Users/akra/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.7.1 - #generating default wrappers........
ruby-2.7.1 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-2.7.1 - #complete
Ruby was built without documentation, to build it run: rvm docs generate-ri

== Installing Ruby dependencies ==
The Gemfile's dependencies are satisfied

== Installing Appraisals ==
>> bundle check --gemfile='/Users/akra/Labs/shoulda-matchers/gemfiles/rails_5_0.gemfile' || bundle install --gemfile='/Users/akra/Labs/shoulda-matchers/gemfiles/rails_5_0.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/akra/Labs/shoulda-matchers/gemfiles/rails_5_1.gemfile' || bundle install --gemfile='/Users/akra/Labs/shoulda-matchers/gemfiles/rails_5_1.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/akra/Labs/shoulda-matchers/gemfiles/rails_5_2.gemfile' || bundle install --gemfile='/Users/akra/Labs/shoulda-matchers/gemfiles/rails_5_2.gemfile' --retry 1
The Gemfile's dependencies are satisfied
>> bundle check --gemfile='/Users/akra/Labs/shoulda-matchers/gemfiles/rails_6_0.gemfile' || bundle install --gemfile='/Users/akra/Labs/shoulda-matchers/gemfiles/rails_6_0.gemfile' --retry 1
The Gemfile's dependencies are satisfied

Setup complete!
```

**Comment by VSPPedro** [comment]
Worked for me! Thanks!

**Review by VSPPedro — APPROVED** [review]

**Comment by mcmire** [comment]
Perfect, thank you! Merging.

**Comment by mcmire** [comment]
This change is now present in setup_script_generator 0.4.0 [here](https://github.com/mcmire/setup_script_generator/commit/19a39be009fce049ab8e3d7cb2c0c431d385bd0c), so if we end up regenerating the setup script we can use that version (or anything later) without blowing this change away.

**Pull request merged**
